
# Authors: 
#         Alfredo Sanchez-Tojar, MPIO (Seewiesen) and ICL (Silwood Park), alfredo.tojar@gmail.com
#         Damien Farine, MPIO (Radolfzell) and EGI (Oxford), dfarine@orn.mpg.de

# Script first created on the 27th of October, 2016

###############################################################################
# Description of script and Instructions
###############################################################################

# This script aims to generate a figure that shows the variety of hierarchy
# scenarios explored.


###############################################################################
# Packages needed
###############################################################################

# packages needed to be loaded for this script (a couple of them might be only needed in the following
# script)



# Clear memory and get to know where you are
rm(list=ls())


###############################################################################
# Functions needed
###############################################################################

plot_winner_prob <- function(diff.rank, a, b,coline) {
  
  diff.rank.norm <- diff.rank/max(diff.rank)
  
  lines(diff.rank, 0.5+0.5/(1+exp(-diff.rank.norm*a+b)),col=coline)
  
}


###############################################################################
# Multi-pannel plot to explore parameter space (i.e. hierarchy scenarios)
###############################################################################

avalues <- seq(0,30,5)
bvalues <- seq(-5,35,5)

a1 <- c("(a)","(b)","(c)","(d)","(e)","(f)","(g)","(h)","(i)")
colours <- brewer.pal(7,"Set1")


tiff("plots/Figure1_Exploring_parameter_space.tiff", 
     height=29.7, width=21,
     units='cm', compression="lzw", res=600)

par(mfrow=c(3,3))

# For each value of b plot all the curves generated by changing the value of a

for (i in 1:length(bvalues)){
  
  plot(c(1,50),c(0,1),type="n",
       ylab="P of higher rank winning", xlab="Difference in rank")
  
  for (j in 1:length(avalues)){
    coline <- colours[j]
    plot_winner_prob(1:50,a=avalues[j],b=bvalues[i],coline)

  }

  lines(c(0,52),c(0.5,0.5),col="red",lty=3,lwd=1.5) # line at randomness, i.e. P=0.5
    
  btext <- paste("\nb = ",bvalues[i])
  text(46,0.02,a1[i],adj = 0)
  text(34,0.245,btext,adj = 0,cex=1.35)
  
  par(xpd=TRUE)
  legend(0,0.2,
         c("a = 0","a = 5","a = 10","a = 15"),
         col=colours[1:4],
         cex=0.8,bty='n',
         pch=rep(19,4),
         inset=c(0,0))
  
  legend(12,0.2,
         c("a = 20","a = 25","a = 30"),
         col=colours[5:7],
         cex=0.8,bty='n',
         pch=rep(19,4),
         inset=c(0,0))
  
}

dev.off()